server:
  servlet:
    contextPath: /esword-api
spring:
  application:
    name: esword-api
  datasource:
    url: jdbc:sqlite::resource:bibles/kjv+.bbli
    driverClassName: org.sqlite.JDBC
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
  endpoint:
    health:
      probes:
        enabled: true